apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynode-deployment
  labels:
    app: node
spec:
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
        containers:
          - name: mynode-con
            image: mushahid144/my-node:v1
            startupProbe:
              exec:
                command:
                  - "curl"
                  - "http://mydb:27017"
              initialDelaySeconds: 10
              periodSeconds: 10
              failureThreshold: 2
            readinessProbe:
              httpGet: 
                path: /home
                port: 4000
              initialDelaySeconds: 10
              periodSeconds: 10
              timeoutSeconds: 4
              failureThreshold: 2
              successThreshold: 1
            livenessProbe:
              httpGet: 
                path: /home
                port: 4000
              initialDelaySeconds: 10
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 5
              successThreshold: 1


