apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deploy
  labels:
    app: database
spec:
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      volumes:
        - name: mongovol
          persistentVolumeClaim:
            claimName: mongo-pvc
      containers:
        - name: mongo-cont
          image: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "mushahid"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "redhat"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongovol
              mountPath: /data/db
