apiVersion: apps/v1
kind: Deployment
metadata:
  name: myreact-deployment
  labels:
    app: react
spec:
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
        containers:
          - name: myreact-con
            image: mushahid144/my-react:v1
            env:
              - name: serverHost
                value: "mynode"
              - name: port
                value: "4000"


            startupProbe:
              exec:
                command:
                  - "curl"
                  - "http://mynode:4000/home"
              initialDelaySeconds: 10
              periodSeconds: 10
              failureThreshold: 2
            livenessProbe:
              httpGet: 
                path: /
                port: 5173
              initialDelaySeconds: 10
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 5
              successThreshold: 1


