apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - database/pv.yaml
  - database/pvc.yaml
  - database/deployment.yaml
  - database/svc.yaml

  - backend/deployment.yaml
  - backend/service.yaml

  - frontend/deployment.yaml
  - frontend/svc.yaml

