
services:
  database:
    container_name: mydb
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: redhat
    networks:
      - mynetwork
    

  backend:
    depends_on:
      - database
    container_name: mynode
    image: 'mushahid144/my-node:v1'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: redhat
      HOST: mydb
    networks:
      - mynetwork
    expose:
      - 4000

  frontend:
    depends_on:
      - backend
    container_name: myreact
    build:
      context: ../frontend/Docker/
      # dockerfile: React
    image: mushahid144/my-react:v1
    environment:
      BACKEND_HOST: mynode
      BACKEND_PORT: 4000
    networks:
      - mynetwork
    expose:
      - 5173
    ports:
      - 80:5173


networks:
  mynetwork:
    driver:  bridge
